---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/treindev/trein.os
name: trein.os
description: Atomic niri desktop environment with dms. Based on Fedora 44

base-image: ghcr.io/ublue-os/base-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* the image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter

  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - scottames/ghostty
    install:
      packages:
        - niri
        - dms
        - dms-greeter
        - distrobox
        - btop
        - fish
        - ghostty
        - ddcutil
        - mako
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - nautilus
        - polkit-kde
        - ddcutil
        - libvirt-daemon-config-network
        - libvirt-daemon-kvm
        - qemu-kvm
        - virt-install
        - virt-manager
    remove:
      packages:
        - alacritty
        - firefox
      auto-remove: true

  - type: systemd
    system:
      enabled:
        - greetd.service
    user:
      enabled:
        - mako.service
        - plasma-polkit-agent.service
        - init-devbox.service
  
  - type: script
    snippets:
      - mkdir -p /etc/systemd/user/niri.service.wants
      - ln -s /usr/lib/systemd/user/dms.service /etc/systemd/user/niri.service.wants/dms.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - com.valvesoftware.Steam
          - com.usebottles.bottles
          - org.freedesktop.Platform.VulkanLayer.gamescope
          - org.prismlauncher.PrismLauncher
          - com.discordapp.Discord
          - org.fedoraproject.MediaWriter
          - com.actualbudget.actual
          - org.fedoraproject.MediaWriter

  - type: signing
